# Generated by Django 3.2.16 on 2023-01-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
