# Generated by Django 3.2.16 on 2023-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.ManyToManyField(related_name='products', to='products.ProductRating'),
        ),
    ]
