# Generated by Django 3.2.16 on 2023-02-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230202_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='rating',
            new_name='score',
        ),
    ]
