# Generated by Django 3.2.16 on 2023-02-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230204_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
