# Generated by Django 3.2.16 on 2023-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20230216_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.ManyToManyField(related_name='products', to='products.ProductRating'),
        ),
    ]
