# Generated by Django 3.2.16 on 2023-03-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
