# Generated by Django 3.2.16 on 2023-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230129_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
