# Generated by Django 3.2.16 on 2023-01-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinfo_post_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user info', 'verbose_name_plural': 'users info'},
        ),
    ]
