# Generated by Django 3.2.16 on 2023-03-11 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230223_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='birth_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
