# Generated by Django 3.2.16 on 2023-03-12 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='full_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Please enter a valid full name!', regex="/^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$")]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('DoNotShow', 'Do not show')], max_length=9, null=True),
        ),
    ]
