# Generated by Django 3.2.16 on 2023-03-17 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230315_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)])),
                ('discount', models.IntegerField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
