# Generated by Django 3.2.16 on 2023-04-07 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
