# Generated by Django 3.2.16 on 2023-03-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_basket', '0004_alter_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_ordered',
        ),
    ]
