# Generated by Django 3.2.16 on 2023-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_basket', '0005_remove_basket_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
