# Generated by Django 3.2.16 on 2023-03-18 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_basket', '0006_basket_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
