# Generated by Django 3.2.16 on 2023-03-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_basket', '0007_basket_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='order_date',
        ),
    ]
